#!/usr/bin/env python
# -*- coding: utf-8 -*-
MEDIAS = {
    '20 Minutes': ["20Minutes", "20minutesOnline", "20minutesplanet", "20minutesSport", "20minutesTech",
                   "20minutesparis", "20min_Sports", "20minuteslyon", "20minutesCult", "20minutesrennes",
                   "20minutestoul", "20minutesMars", "20minuteslille", "20minutesEco", "20minutesnantes"],
    'Agence Centrale De Presse': ['ACP_Presse'],
    'Arrets Sur Images': ["arretsurimages"],
    'Atlantico': ["atlantico_fr"],
    "Avenir De L'Artois": ["avenirartois"],
    'Bfm Business': ["bfmbusiness"],
    'Bfmtv': ["BFMTV", "20HPolitique", "BFMTV_People", "BFMTV_Inside", "BFMTVNewsDesk", "PremiereEdition", "LeSoirBFM",
              "BFMSportTV", "BFMPolitique", "BFM_Tech"],
    'Canal +': ["canalplus", "CanalFootClub", "CanalRugbyClub"],
    'Capital': ["MagazineCapital"],
    'Centre Presse Aveyron': ["CPAveyron"],
    'Centre Presse Poitiers': ["centre_presse"],
    'Challenges': ["Challenges"],
    'Corse Matin': ["Corse_Matin", "cm_musique"],
    'Courrier Cauchois': ["lccauchois"],
    "Courrier De L'Eure": ["CourrierdelEure"],
    'Courrier De La Mayenne': ["CDLM53"],
    'Courrier Du Pays De Retz': ["CourrierRetz"],
    'Courrier Independant': ["CILoudeac"],
    'Courrier Vendeen': ["Courriervendeen"],
    # 'Democrate Independant-Le Journal De Bergerac': ["Demoredac"],
    'Democrate Vernonnais': ["LDmocrate"],
    # "Depeche D'Auvergne": [],
    'Depeche Du Bassin': ["Depechedubassin"],
    # 'Depeche Du Pays De Bray': [],
    'Direct Matin': ["directmatin"],
    # 'Direct Soir': ["Direct Soir", "DirectSoir"],
    # 'Echo De L\'Armor Et De L\'Argoat': [],
    # 'Echo De L\'Ouest': [],
    # 'Echo Charitois': [],
    'Echo De La Lys': ["echodelalys"],
    # 'Echo Du Berry': [],
    # 'Echo Du Thelle': [],
    'Echo Sarthois': ["EchoSarthois"],
    'Echos Du Touquet': ["echostouquet"],
    'Est Eclair': ["lesteclair", "lesteclairSport"],
    'Euronews': ["euronewsfr"],
    'Europe 1': ["Europe1", "E1PPDE", "carnetsdumonde", "leLab_E1"],
    # 'Eveil De Lisieux': [],
    # 'Eveil De Pont Audemer': [],
    'Eveil Normand': ["Eveil_Normand"],
    'France Soir': ["france_soir"],
    # 'Gazette': [],
    # 'Gazette Ariegeoise': [],
    # 'Gazette De La Loire': [],
    'Gazette De La Manche': ["Gazette50"],
    # 'Gazette De Montpellier': [],
    'Haut Anjou': ["HautAnjou"],
    'Haute Provence Info': ["HPInfo"],
    # 'Havre Libre': [],
    # 'Havre Presse': [],
    # 'Hebdo De Charente Maritime': [],
    # "Hebdo De L'Ardeche": [],
    # 'Hebdo Vendee': [],
    'Impartial De La Drome': ["limpartial26"],
    # 'Independant Du Louhannais Et Du Jura': [],
    'Indicateur Des Flandres': ["indicflandres"],
    # 'Informateur': [],
    'Infos Pays De Redon': ["LesInfosRedon"],
    # 'Itele': [],
    "Journal D'Elbeuf": ["JournaldElbeuf"],
    "Journal D'Ici": ["LeJournaldIci"],
    # 'Journal De Gien': ["LeJournaldeGien"],
    # 'Journal De Ham': ["JournaldeHam"],
    "Journal De L'Orne": ["Journaldelorne"],
    'Journal De Vitre': ["JdeVitre"],
    # 'Journal Du Medoc': ["JournalduMedoc"],
    # 'Journal Liberte': [],
    "L'Aisne Nouvelle": ["aisnenouvelle"],
    "L'Alsace": ["lalsace"],
    "L'Ardennais": ["UnionArdennais"],
    # "L'Aurore": [],
    # "L'Echo Du Centre": [],
    "L'Echo Republicain": ["lecho_fr"],
    # "L'Eclair Pyrenees": [],
    # "L'Eclair de Nantes": [],
    # "L'Equipe": ["lequipe", "lachainelequipe", "lequipedestelle", "lequipedusoir", "lequipetype", "lequipeEXPLORE"],
    "L'Est Republicain": ["lestrepublicain", "LEstRepVesoul", "LEstSportsLO", "LEstRepLure", "LEstRepMontbe",
                          "LEstRepBelfort", "LEstRepLun", "Lestrepverdun", "LEstRepPam", "LEstRepBesac",
                          "LEstRepBarleDuc", "LEstRepToul", "LEstRepNancy", "LEstRepHtDoubs"],
    "L'Eveil de la Haute Loire": ["leveil43"],
    # "L'Expansion": ["LEXPANSION_actu"],
    "L'Express": ["LEXPRESS", "express_region", "LEXPRESS_cult"],
    "L'Humanite": ["humanite_fr"],
    "L'Independant": ["lindependant", "LIndep_perpi", "Narbonne_lindep", "Carca_lindep", "sport_lindep"],
    # "L'Information": [],
    # "L'Union": ["UnionArdennais"],
    "L'Yonne Republicaine": ["lyonne_fr", "lyonne_sports"],
    'La Charente Libre': ["charentelibre"],
    'La Croix': ["LaCroix"],
    'La Depeche du Midi': ["ladepechedumidi"],
    # 'La Dordogne Libre': [],
    # 'La France La Nouvelle Republique': [],
    # 'La Gazette De Thiers': [],
    # 'La Liberte du Morbihan': [],
    # 'La Liberte Du Massif Central': [],
    'La Marseillaise': ["lamarsweb"],
    'La Montagne': ["lamontagne_fr", "sportlamontagne", "Montagnecorreze", "montagnethiers", "lamontagne_15",
                    "lamontagne_riom", "Montagne_Vichy", "MontagneMoulins", "montagnetulle", "montagne_creuse",
                    "montagnestflour", "montagneussel", "MontagneBrioude"],
    'La Nouvelle République': ["nrpoitiers", "LaNRSports", "nrchateauroux", "NRNiort", "nrbressuire", "NRBlois",
                               "NRVendome"],
    'La Nouvelle Republique des Pyrenees': ["nrpyrenees"],
    'La Presse de la Manche': ["LaPresseManche"],
    'La Provence': ["laprovence", "OMLaProvence", "LaProvenceAlpes", "LaProvenceAix", "LaProvenceMars", "LP_Martigues",
                    "LaProvenceSport", "LPAvignon"],
    # 'La Republique Des Pyrenees': [],
    'La Republique du Centre': ["larep_fr"],
    'La Tribune': ["LaTribune", "LaTribuneTlse", "LaTribuneBdx", "latribunedespme", "LaTribunePACA"],
    'La Vie': ["LaVieHebdo"],
    'La Voix Du Nord': ["lavoixdunord", "VDNRoubaix", "VDNDouai", "VDNCalais", "VDNValenciennes", "VDN_Boulogne",
                        "VDNHenin", "voixdunordarras", "VDNSeclin", "VDNLambersart", "VDNLille", "VDNDunkerque",
                        "VDNLens", "vdascq", "VDNMaubeuge", "VDNetaples", "VDNtourcoing", "AvesnesVDN",
                        "VDNHazebrouck"],
    'Lci': ["LCI", "LCIPolitique", "LaMatinaleLCI"],
    'Le Berry Republicain': ["leberry_fr"],
    'Le Bien Public': ["Lebienpublic", "BienPublicSport", "BP_Montbard"],
    'Le Canard Enchaine': ["canardenchaine"],
    "Le Courrier De L'Ouest": ["courrierouest", "coCholet", "coNiort", "coSaumur"],
    # 'Le Courrier De Saone Et Loire': [],
    'Le Courrier Picard': ["CourrierPicard"],
    'Le Dauphine Libere': ["ledauphine", "dauphinevienne", "LeDL73", "LeDLVaucluse", "LeDL05et04", "DL_Sports38",
                           "LeDLisere", "LeDL_Grenoble", "DLSports74", "DLsportgrenoble", "LeDL26et07"],
    'Le Figaro': ["Le_Figaro", "Figaro_Etudiant", "Figaro_Histoire", "FigaroPolitique", "FigaroPlume",
                  "Figaro_Sciences",
                  "FigaroTech"],
    # 'Le Haut Marnais Republicain': [],
    'Le Huffington Post': ["LeHuffPost"],
    'Le Journal De Saone Et Loire': ["lejsl"],
    'Le Journal Du Dimanche': ["leJDD"],
    # 'Le Journal Du Pas De Calais Et De La Somme': [],
    # 'Le Journal Rhone Alpes': [],
    # 'Le Journal de la Haute Marne': [],
    'Le Journal du Centre': ["lejdc_fr", "lejdc_sports"],
    'Le Maine Libre': ["lemainelibre"],
    # 'Le Matin De Paris': [],
    # 'Le Meridional': ["LeMeridionalfr"],
    'Le Monde': ["lemondefr", "lemonde_M", "LeMondeEduc", "lemonde_culture", "LeMondeTV", "lemonde_cities", "LeMondeEcoEnt"],
    'Le Monde Diplomatique': ["mdiplo"],
    # 'Le Nouveau Rhin Francais': [],
    # 'Le Nouvel Alsacien': [],
    "L'Obs": ["lobs", "Obs_Eco", "lobs_live", "OleMag"],
    'Le Parisien': ["le_Parisien", "LeParisien_91", "LeParisien_93", "LeParisien_60", "LeParisienWE", "leParisien_pol",
                    "LeParisien_92", "P_etudiant", "LeParisien_75", "parisiensortie", "LeParisienInfog",
                    "leparisien_turf", "LeParisien_94", "LeParisien_Auto", "ParisienMusique", "LeParisien_Tele",
                    "LeParisien_Cine", "TransportsIDF", "le_Parisien_PSG"],
    # 'Le Patriote De Saint Etienne': [],
    # 'Le Patriote Du Centre Et Du Sud Est': [],
    'Le Petit Bleu': ["petitbleuagen"],
    'Le Point': ["LePoint", "LePointAuto", "LePointVin", "LePointInnov", "LePointAfrique"],
    'Le Populaire du Centre': ["lepopulaire_fr", "lepopu_sports"],
    # 'Le Post': ["LePost"],
    'Le Progres': ["Le_Progres", "ProgresFirminy", "LPRhauteloire", "leprogres_asse", "leprogreslyon",
                           "Leprogresloire", "ProgresRunning", "leprogreseco", "leprogres_forez", "leprogrestarare",
                           "leprogresphoto", "Progres_Roanne"],
    # 'Le Provencal': ["LeProvencalinfo"],
    'Le Republicain Lorrain': ["lerepu", "rl_metz", "RLSaintAvold", "RLMoselleNord"],
    "Le Telegramme": ["LeTelegramme", "TLGMorlaix", "TelegVannes", "TLGQuimper", "TelegrammeGGP", "TlgrammeLannion",
                      "TelegPaimpol", "TelegLorient", "TelegrammeDinan", "TLGBrest", "TelegrammeSport", "TLGQuimperle",
                      "TLGCarhaix", "telegchateaulin", "LeTelegrammeEco"],
    'Les DNA': ["dnatweets"],
    # 'Les Depeches': [],
    'Les Echos': ["LesEchos", "EchosAuto", "CercleLesEchos", "EchosAirDefense", "EchosMonde", "Echos_Solutions",
                  "EchosModeLuxe", "LesEchosWeekEnd", "LesEchosPME"],
    'Les Infos Dieppoises': ["infosdieppoises"],
    'Les Inrocks': ["lesinrocks"],
    'Liberation': ["libe", "Libe_Eco", "LibeVoyages", "LibeMonde", "libevideo", "LibeIdees", "Libe_Sports"],
    # 'Liberation Champagne': [],
    'Liberte Hebdo': ["LibHebdo"],
    # 'Libre Artois': [],
    # 'Littoral De La Charente Maritime': [],
    # 'Lyon Matin': [],
    'M6': ["M6", "M6MusicOfficiel", "m6evenements"],
    'Marianne': ["MarianneleMag"],
    # 'Maurienne': [],
    'Mediapart': ["Mediapart", "MediapartLive", "Mediapart_Inter"],
    # 'Messager': [],
    # 'Metrofrance': ["metrofrance", "metronews"],
    'Midi Libre': ["Midilibre", "MLMontpellier", "MidiLibreNimes", "MidiLibreMillau", "MLBeziers", "MidiLibreAude",
                   "MidiLibreSete", "MidiLibreSports", "MidiLibrelozere", "MidiLibreAles", "MidiLibreLunel",
                   "Culture_ML", "MidiLibre_Eco", "MidilibreLive", "MLGardrhodanien"],
    'Nice Matin': ["Nice_Matin", "NiceMatinEco", "NMcannes"],
    'Nord Eclair': ["NordEclairRbx", "NordEclairWeb", "NordEclairLens", "NordEclairLille", "nordeclair",
                    "NordEclairLys", "NordEclairTg"],
    'Nord Littoral': ["Nordlitt"],
    # 'Nord Matin': [],
    'Nouvelles De Falaise': ["lesnouvelles14"],
    'Observateur De Beauvais': ["lobsdebeauvais"],
    # "Observateur De L'Arrageois": [],
    # "Observateur De L'Avesnois": [],
    # 'Observateur Du Cambresis': [],
    # 'Observateur Du Douaisis': [],
    # 'Observateur Du Valenciennois': [],
    'Oise Hebdo': ["Oisehebdo"],
    'Orne Combattante': ["OrneCombattante"],
    'Orne-Hebdo': ["LOrneHebdo"],
    'Ouest France': ["OuestFrance", "OuestFrance53", "OuestFrance50", "ofangers49", "OuestFrance85", "ouestfrance35",
                     "OuestFrance44", "OuestFrance72", "leditiondusoir", "sports_ouest", "OuestFrance49",
                     "OuestFrance29", "OuestFrance14", "OuestFrance_56", "OfSport44", "OuestFrance22",
                     "ouestfranceauto"],
    # 'Paris Jour': [],
    'Paris Match': ["ParisMatch", "instantmatch", "Data_Match"],
    'Paris Normandie': ["paris_normandie", "Sport_PN"],
    'Pays Briard': ["LePaysBriard"],
    # "Pays D'Auge": [],
    'Penthievre': ["LePenthievre"],
    'Perche': ["le_perche"],
    # "Petit Bleu Des Cotes D'Armor": [],
    'Petit Courrier De La Vallee Du Loir': ["CourrierEcho"],
    'Phare Dunkerquois': ["pharedk"],
    'Presse Ocean': ["presseocean", "DIRECTPO"],
    # 'Regional De Cosne': [],
    # 'Renaissance': [],
    # 'Renaissance Du Loir Et Cher': [],
    # 'Renaissance Le Bessin Cote De Nacre': [],
    # 'Renouveau': [],
    # "Republicain D'Uzes Et Du Gard": [],
    "Republicain Lot Et Garonne": ["LeRep47"],
    # 'Republicain Sud Gironde': [],
    # 'Resistant': [],
    'Reveil De Neufchatel': ["bray_info"],
    'Reveil Normand': ["ReveilNormand"],
    'Rmc': ["RMCinfo", "RMCsport"],
    # 'Rouen Normandie Nouvelles': [],
    'Rtl': ["RTLFrance"],
    'Rue89': ["Rue89"],
    'Sables Vendee Journal': ["JdSables"],
    # 'Sambre': [],
    # "Savoie La Renaissance L'Echo Des Vallees": ["Lechodesvallees"],
    'Semaine Dans Le Boulonnais': ["semboulonnais"],
    "Semaine De L'Allier": ["semaine03"],
    # "Semaine De Nancy": [],
    # 'Semaine De Nimes': [],
    # 'Semaine Des Pyrenees': [],
    # 'Semaine Du Lot': [],
    # 'Semaine Du Minervais': [],
    # 'Semaine Du Pays Basque': [],
    'Semaine Du Roussillon': ["LaSemaineduRous"],
    # 'Semaine Metz Thionville Moselle': [],
    'Slate': ["Slatefr"],
    'Sud Ouest': ["sudouest", "SO_Gourmand", "SO_Bordeaux", "SO_Libourne", "SudOuest_Sport", "SO_LaRochelle",
                  "SudOuestEco", "SO_Dordogne"],
    # 'Tarn Infos': [],
    # 'Tarn Libre': [],
    'Tregor': ["LeTregor"],
    'Tribune De Lyon': ["tribunedelyon"],
    # 'Tribune De Vienne': [],
    # 'Tribune PHR': [],
    'Tribune Republicaine': ["LaTribuneRepub"],
    'Union Du Cantal': ["LunionduCantal"],
    'Var Matin': ["Var_Matin", "Varmatin_Hyeres", "Var_matin_sport", "VM_FrejusStRaph", "VMlaseyne", "VMtoulon",
                  "VMdraguignan", "VMCentreVar"],
    'Vie Charentaise': ["VieCharentaise"],
    # 'Vie Nouvelle': [],
    'Vie Quercynoise': ["actulot"],
    'Villefranchois': ["Villefranchois"],
    "Voix De L'Ain": ["voixdelain"],
    # 'Voix De La Haute Marne': ["VoixHauteMarne"],
    'Voix Du Cantal': ["lavoixducantal"],
    'Voix Du Jura': ["VoixduJura"],
    # 'Voix Du Midi': [],
    # 'Voix Du Sancerrois': [],
    'Voix Le Bocage': ["lavoixlebocage"],
    'Vosges Matin': ["VosgesMatin", "VOMsports", "VosMatin_Epinal"],
    # Ajouts de ma part:
    'TF1': ["TF1"],
    # 'France Televisions': [],
    'France 3': ['France3tv', "F3PoitouChtes", "F3Alsace", "F3Aquitaine", "F3htenormandie", "F3nord", "F3Picardie",
                 "F3Bourgogne", "F3Languedoc", "France3CA", "F3PaysdelaLoire", "F3Lorraine", "F3Rhone_Alpes",
                 "France3Paris", "f3Alpes", "france3Bretagne", "FTViaStella", "France3Presse", "F3Centre",
                 "France3MidiPy", "F3Limousin", "F3bnormandie", "France3Provence"],
    'France 2': ["France2tv", "20hFrance2", "Cdenquete", "cashinvestigati", "13h15", "EnvoyeSpecial"],
    'France 5': ["France5tv", "CaDireF5"],
    "France Bleu": ["francebleu", "bleuprovence", "bleustetienne", "BleuAlsace", "Bleu_Gironde", "bleuloireocean", "fbleupicardie", "fbleunord", "bleusudlorraine",
                    "Bleu_Poitou", "fbleuchampagne", "fblorrainenord", "francebleuDA", "fbleubnormandie", "bleugardlozere", "fbleuhnormandie", "bleuherault",
                    "francebleuParis", "bleumayenne", "bleuvaucluse", "bleuroussillon", "Bleu_Basque", "FBLimousin", "BleuElsass", "bleuauxerre",
                    "bleubelfort", "bleumaine", "bleusavoie", "Bleu_Rochelle", "FBTouraine", "Bleu_Gascogne", "FBAuvergne", "francebleuazur",
                    "fbleu_musique", "BleuOccitanie", "Bleu_Perigord"],
    'AFP': ['afpfr'],
    'France Inter': ["franceinter"],
    'Franceinfo': ["franceinfo", "franceinfoplus"],
    'Les Jours': ["Lesjoursfr"],
    'The Conversation': ["FR_Conversation"],
    'Le 1': ['Le1hebdo'],
    'Contexte': ["Contexte", "contexte_local", "ContextePouvoir", "Contexte_Transp", "contexte_num", "contexteenergie"],
    'Alternatives Economiques': ["AlterEco_"],
    'Courrier International': ["courrierinter"],
    'Society': ['SocietyOfficiel'],
    'France Culture': ["franceculture", "FCulture_Pol", "Lesmatinsfcult"],
    'Arte': ['ARTEfr'],
    'RFI': ['RFI'],
    'France 24': ['France24_fr', "PolitiqueF24", "UrgentF24", "F24videos", "SportF24", "DebatF24", "F24MoyenOrient",
                  "F24Afrique"],
    'TV5 Monde': ['TV5MONDE', "TV5MONDEAsia", "TV5MONDEINFO", "TV5MONDEAfrique"]
}

listemedias = []
for media in MEDIAS.keys() :
    for elt in MEDIAS[media] :
        listemedias.append(elt)
